### ISSUE TITLE
Criar sistema de câmera

### ISSUE THREAD

**Issue by Vitor-Calegari** [INE-UFSC/projeto-final-grupo-5-23-1#2]
A câmera do jogo deve seguir o jogador durante sua jogatina, e por isso precisamos de um sistema capaz de realizar isso!

- [x] Implementar sistema de câmera

- Obs: Essa issue deve ser feita após a issue de criação do mapa pelo Tiled.

**Comment by robertotxr** [comment]
Posso ficar com essa
